language: objective-c
osx_image: xcode8
rvm: 2.3.0
install:
  - bundle install
  - travis_wait 30 bundle exec pod repo update --silent
  - travis_wait 30 bundle exec pod install
before_script:
  - ./script/disable_sparkle.sh
script:
  - set -o pipefail && xcodebuild -workspace Hakumai.xcworkspace -scheme Hakumai -configuration Debug -destination 'platform=OS X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | bundle exec xcpretty -c
cache:		 
  - bundler 
  - cocoapods
